services:
  ollama-cpu:
    image: ollama/ollama
    container_name: ollama_cpu
    devices:
      - /dev/dri:/dev/dri
    environment:
      - OLLAMA_DEBUG=1
    ########
    volumes:
      - ./ollama:/root/.ollama
    # expose:
    #   - 11434
    ports:
      - 11434:11434
    restart: unless-stopped
    # networks:
    #   - shared-network


    # networks:
    #   shared-network:
    #     external: true
